_target_: model.MLP
initial_out_features: 2
sizes: [1024, 400, 400]
layers: ["ReLUKAN", "ReLUKAN"]
head_type: ReLUKAN
# activation:
#   _target_: torch.nn.ReLU
activation: IntervalActivation
mask_past_classifier_neurons: False
config:
  - k: 4  # head layer
  - k: 4  # layer 0
  - k: 4  # layer 1