defaults:
  - _self_
  - dataset: mnist
  - scenario: class_inc
  - model: mlp_with_learnable_relu
  - method: composer_interval_penalization_mlp_with_learnable_relu
  - exp: training

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}