defaults:
  - _self_
  - dataset: mnist
  - scenario: class_inc
  - model: mlp_kan
  - method: composer_naive
  - exp: training

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}

method:
  lr: 0.001

exp:
  seed: 42
  batch_size: 256
  epochs: 10
