run_func:
    _target_: experiment.experiment
seed: 1
log_dir: # set during runtime to automatically created dir
batch_size: 512
epochs: 1
gen_cm: False
log_per_batch: False
detect_anomaly: False
cleanup: True
dil: False